[server]
# Change default port
port = 8501
# Allow access from other machines (important for deployment)
address = "0.0.0.0"
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
base="light"
primaryColor="#28a745"             # Brand green (for buttons, highlights)
backgroundColor="#f8f9fa"          # Very light background
secondaryBackgroundColor="#e9ecef" # Slightly darker for sidebar/cards
textColor="#212529"                # Dark gray for readability
font="sans serif"                  # Clean and modern

